[package]
name = "pico_rs_blank"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rp-pico = "0.9.0"
embedded-hal = "1.0.0"
panic-halt = "0.2.0"
cortex-m-rt = "0.7.4"
cortex-m = "0.7.7"